### ISSUE TITLE
Locker

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [vposd/CachedQueries#19]
The dictionary in the locker is never cleared up, the TimeSpan passed on in LockAsync but not actually used when awaiting the semaphore, and if _cache.SetAsync throws an exception (eg cancellationtoken is cancelled) then the semaphore is not released. Moreover, the cancellationtoken is not being passed onto the semaphore awaiter. I have made a library that you may find useful at https://github.com/MarkCiliaVincenti/AsyncKeyedLock as it solves these issues for you and will decrease memory usage and allocations if you use pooling.

**Comment by vposd** [comment]
Thank you for the suggesting!
Yes, you are right, default lock manager has a naive implementation.
I added some enhancements to it. 
Also, I'm preparing some lock managers implementations for various use cases.

**Comment by MarkCiliaVincenti** [comment]
> Thank you for the suggesting! Yes, you are right, default lock manager has a naive implementation. I added some enhancements to it. Also, I'm preparing some lock managers implementations for various use cases.

Careful. I believe you now introduced a race condition. A thread may be getting from the dictionary while another may be removing from the dictionary. That would allow a third thread to find nothing in the dictionary and concurrently execute for the same key.

If you want I can make a PR to switch to AsyncKeyedLock.

**Comment by MarkCiliaVincenti** [comment]
@vposd you still have race conditions 11 months later :)
